"""Runtime interfaces; Redis schemas never escape the adapter."""
from dataclasses import dataclass
from typing import Protocol
from .models import ExecutionTask, ExecutionLease


@dataclass(frozen=True)
class QueueMessage:
    message_id: str
    execution_id: str
    consumer: str = ''
    idle_ms: int = 0


class ExecutionQueue(Protocol):
    def publish(self, execution_id: str) -> str: ...
    def receive(self, consumer: str, block_ms: int = 100) -> QueueMessage | None: ...
    def pending(self, min_idle_ms: int, count: int = 100) -> list[QueueMessage]: ...
    def reclaim(self, message: QueueMessage, consumer: str, min_idle_ms: int) -> bool: ...
    def ack(self, message: QueueMessage) -> None: ...


class ExecutionStore(Protocol):
    def create(self, task: ExecutionTask) -> ExecutionTask: ...
    def get(self, execution_id: str) -> ExecutionTask | None: ...
    def tasks(self, count: int = 100) -> list[ExecutionTask]: ...
    def now(self) -> float: ...
    def queued(self, execution_id: str) -> ExecutionTask: ...
    def acquire(self, execution_id: str, worker_id: str, lease_seconds: float) -> ExecutionTask | None: ...
    def start(self, lease: ExecutionLease) -> ExecutionTask: ...
    def renew(self, lease: ExecutionLease, lease_seconds: float) -> ExecutionTask: ...
    def attach_recovery(self, lease: ExecutionLease, recovery: dict) -> ExecutionTask: ...
    def finish(self, lease: ExecutionLease, success: bool, result: dict | None, error: dict | None = None) -> ExecutionTask: ...
    def end_attempt(self, lease: ExecutionLease, outcome: dict, error: dict) -> ExecutionTask: ...
    def lose(self, execution_id: str, error: dict) -> ExecutionTask | None: ...
    def recover(self, execution_id: str, controller: str, lease_seconds: float) -> ExecutionTask | None: ...
    def ready(self, lease: ExecutionLease) -> ExecutionTask: ...
    def cancel(self, execution_id: str) -> ExecutionTask: ...


class WorkerRegistry(Protocol):
    def register(self, worker_id: str, metadata: dict, ttl: float) -> None: ...
    def heartbeat(self, worker_id: str, ttl: float) -> bool: ...
    def get(self, worker_id: str) -> dict | None: ...
    def unregister(self, worker_id: str) -> None: ...
